# Testsuite Application Options

# Java memory settings
core.memory.immortal.memory=RAM
core.memory.immortal.size=4096
core.memory.javaheap.memory=RAM
core.memory.javaheap.size=32768
core.memory.javaheapsum.size=32768
core.memory.thread.block.size=512
core.memory.thread.max.size=4
core.memory.threads.memory=RAM
core.memory.threads.pool.memory=RAM
core.memory.threads.pool.size=15
core.memory.threads.size=10

microej.java.property.serial.port.rx=lpuart2
microej.java.property.serial.port.tx=lpuart7
microej.java.property.serial.port.config=115200-8-N-1

###############
# Serial Mock #
###############
# s3.mock.uart.com0.mode=2
# s3.mock.uart.com0.name=lpuart2
# s3.mock.uart.com0.socket.port=7777
# s3.mock.uart.com0.socket.timeout=30000

# s3.mock.uart.com1.mode=2
# s3.mock.uart.com1.name=lpuart7
# s3.mock.uart.com1.socket.port=7778
# s3.mock.uart.com1.socket.timeout=30000

s3.mock.uart.com0.mode=0
s3.mock.uart.com0.name=lpuart2
s3.mock.uart.com0.mapping=COM7

s3.mock.uart.com1.mode=0
s3.mock.uart.com1.name=lpuart7
s3.mock.uart.com1.mapping=COM12